name: NewPrixmix Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: alpine

    steps:
    - uses: actions/checkout@v4
    - name: Build the NewPrixmix Docker Image
      run: docker build . --file Dockerfile --tag newprixmix
